version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.3
        environment:
          MIX_ENV: test

    working_directory: ~/fb

    steps: 
      - checkout 

      - run: mix local.hex --force 
      - run: mix local.rebar --force

      - run: mix deps.get
      - run: mix test
      - run: mix dialyzer
