version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.3
        environment:
          MIX_ENV: test

    working_directory: ~/fe

    steps: 
      - checkout 

      - restore_cache:
          keys:
              - fe-plt-{{ checksum "mix.lock" }}

      - run: mix local.hex --force 
      - run: mix local.rebar --force

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test

      - run: mix dialyzer
      - save_cache:
          key: fe-plt-{{ checksum "mix.lock" }}
          paths:
              - "_build/test"
